apiVersion: v1
kind: Secret
metadata:
  name: autodeployx-secrets
  namespace: autodeployx
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  HUGGINGFACE_API_KEY: ""
  LOCAL_LLM_PATH: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
