apiVersion: v1
kind: Service
metadata:
  name: {{ include "repo-analyzer.fullname" . }}-backend
  labels:
    {{- include "repo-analyzer.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "repo-analyzer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "repo-analyzer.fullname" . }}-frontend
  labels:
    {{- include "repo-analyzer.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "repo-analyzer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
